SEMANTIC_ID_SIZE = 6
ADDITIONAL_SEMANTIC_PATTERN = r"<recommend>\d+"
SEMANTIC_PATTERN = rf"({ADDITIONAL_SEMANTIC_PATTERN}</recommend>)"
SEMANTIC_SERIES_PATTERN = rf"{ADDITIONAL_SEMANTIC_PATTERN}+" + "</recommend>"
EXPLAIN_PATTERN = r"<explain>.*?</explain>$"
